# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('industry', models.CharField(max_length=128)),
                ('sector', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Share'),
        ),
    ]
