# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20160330_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='adj_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
