# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20160330_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set([('share', 'date')]),
        ),
    ]
